theme: remote_theme: fongandrew/hydeout

markdown:  kramdown
highlighter: rouge

# Setup
title: Hydeout ãƒ†ãƒ¼ãƒ
tagline: 'GitHub Pages Hydeout ãƒ†ãƒ¼ãƒ'
description:      'The <a href="http://hyde.getpoole.com" target="_blank">Hyde</a> theme for <a href="http://jekyllrb.com" target="_blank">Jekyll</a>, refreshed.'
url:              https://remotetheme.github.io
baseurl:          '/hydeout'

author:
  name:           'ãµã†ã›ã‚“ğŸˆ Fu-sen.'
  url:            https://balloon.im/

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog' 