remote_theme: fongandrew/hydeout

markdown:  kramdown
highlighter: rouge

# Setup
title: Hydeout ãƒ†ãƒ¼ãƒ
tagline: 'GitHub Pages Hydeout ãƒ†ãƒ¼ãƒ'
description: 'GitHub Pages Hydeout ãƒ†ãƒ¼ãƒ'
url: https://remotetheme.github.io
baseurl: '/hydeout'

author:
  name:           'ãµã†ã›ã‚“ğŸˆ FU-SEN'
  url:            https://balloon.im/

paginate:         5
# paginate_path:    '/page:num'

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap

sidebar_home_link:  true
# sidebar_blog_link:  '/blog'

include:
  - _posts
